### ISSUE TITLE
/sci/ board sticky'd moderator thread's OP image is broken but only in catalog view

### ISSUE THREAD

**Issue by Palmput** [TuxedoTako/4chan-xt#125]
https://boards.4chan.org/sci/
https://boards.4chan.org/sci/thread/15833831

![Screenshot 2024-11-19 at 15-11-44 _sci_ - Science   Mat](https://github.com/user-attachments/assets/dcf5fd47-9939-4501-ad3b-1b0a33124fbd)

Noticed this started happening a few weeks ago, but even through various updates to XT and other things and power cycles, it's still like this. As you can see, the image loads in the thread itself as well as in the other board viewing modes.

**Comment by TuxedoTako** [comment]
I can't reproduce the issue on windows. I tested in chome, firefox and edge.

![firefox_Cdi9GEg6QV](https://github.com/user-attachments/assets/845e42ea-234f-4b4b-9c0d-eb7a72d9650a)

**Comment by saxamaphone69** [comment]
It's gone for me on Windows 11, Chrome and Firefox, on index, on catalog, and in thread, with or without 4chan XT enabled.

Funnily enough, the full size image still works just fine, just not the thumbnail.
https://i.4cdn.org/sci/1698861914726429s.jpg
https://i.4cdn.org/sci/1698861914726429.jpg

You could add this to your Custom CSS (4chan XT Settings > Advanced):

```css
#f15833831 > .fileThumb {
  background-image: url('https://i.4cdn.org/sci/1698861914726429.jpg');
  background-size: contain;
  img:first-child {
    visibility: hidden;
    pointer-events: none;
  }
}
```
