### ISSUE TITLE
Other scripts and embeds missing icons

### ISSUE THREAD

**Issue by Toora** [TuxedoTako/4chan-xt#28]
I'm not getting icons on Youtube links and other scripts like OneeChan, sounds player, and imgur thumbnail (that embeds stuff from imgur/catbox etc.). X-links gallery seems to work for some reason however.

4chan XT
![2024-01-31 10_43_36 (2210)_vt_-_#_-_Numbers_-_Virtual_YouTubers_-_4cha](https://github.com/TuxedoTako/4chan-xt/assets/2768885/5a0ccf29-f69b-490e-ab46-013f492eac67)
4chan X
![2024-01-31 10_42_48 (1710)_vt_-_#_-_Numbers_-_Virtual_YouTubers_-_4cha](https://github.com/TuxedoTako/4chan-xt/assets/2768885/44b76220-ef9a-45c0-bbb0-6cb1a834e015)

Is this a permission issue maybe, or something with XT?

**Comment by TuxedoTako** [comment]
When I moved the build from what 4chan X uses to Rollup, I missed that the CSS class for those icons are in lower case. This will be fixed in the next release.

**Comment by TuxedoTako** [comment]
Should be fixed in [2.4.4](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by Toora** [comment]
The embed icons are back, thanks.

As for Oneechan and such that seems to be a different issue. The icons used seem to be from "Font Awesome", something that is included in 4chan X under CSS. So for in the screenshot the Imgur Settings would be using "fa fa-info-circle" and Oneechan "fa fa-gears". Not sure what's up with Sounds, but guess that's not needed.

Is this something that could be included in XT? I don't really get how it works.

**Comment by saxamaphone69** [comment]
```css
:root.fourchan-xt.shortcut-icons #header-bar .fa {
	font-size: 0;
}
:root.fourchan-xt.shortcut-icons #header-bar .fa-play-circle::before {
	content: '♪';
	font-size: 20px;
	line-height: 12px;
}
:root.fourchan-xt.shortcut-icons #header-bar .fa-gears::before {
	content: '⚙';
	font-size: 20px;
	line-height: 12px;
}
```

Then, as you may have guessed, if you want the imgur one, similar selector but `.fa-info-circle` instead and within the content, whichever unicode 'icon' you like the best. And you can adjust the font size as needed.
