### ISSUE TITLE
Feature request - Option to remove options from Quick Reply

### ISSUE THREAD

**Issue by dpython** [TuxedoTako/4chan-xt#46]
I'd like to be able to disable the edit in tegaki, Post from URL, and dump list posting options from the quick reply if possible.

I like to post from tabbing to the submit button
but those other posting options in the quick reply make it kind of annoying to do, having to tab over them first.

Is there a way to remove those options from the quick reply window?

**Comment by TuxedoTako** [comment]
You can hide them with CSS, that way they aren't keyboard focusable.

```CSS
#qr-oekaki-button,
#dump-button,
#url-button {
	display: none !important;
}
```
